---
- name: Deploy Web Application
  hosts: xpemonitor02
  become: true
 
  vars:
    web_root: /usr/share/nginx/html
    app_name: "Ansible Web App"
 
  tasks:
    - name: Install NGINX
      package:
        name: nginx
        state: present
 
    - name: Ensure NGINX is running and enabled
      service:
        name: nginx
        state: started
        enabled: true
 
    - name: Deploy web application
      copy:
        content: 'Xpertal'
        dest: "{{ web_root }}/index.html"
        owner: root
        group: root
        mode: '0644'
 
    - name: Open HTTP port (firewalld)
      firewalld:
        service: http
        permanent: true
        state: enabled
      when: ansible_facts.os_family == "RedHat"
 
    - name: Reload firewall
      service:
        name: firewalld
        state: reloaded
      when: ansible_facts.os_family == "RedHat"
